FROM node:22-alpine

WORKDIR /app

# Install json-server (locking version for reliable behavior)
RUN npm install -g json-server@0.17.4

# Copy db.json
COPY mock/db.json ./db.json

EXPOSE 3000

# Start json server
CMD ["json-server", "--watch", "db.json", "--port", "3000", "--host", "0.0.0.0"]
